#端口和上下文配置
server:
  port: 8070
  servlet:
    context-path: /admin

#spring应用和数据源配置
spring:
  application:
    name: module-admin
  datasource:
    url: jdbc:mysql://localhost:3306/study-cloud-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 0



