#端口和上下文配置
server:
  port: 8081
  servlet:
    context-path: /goods

#spring应用和数据源配置
spring:
  application:
    name: module-goods
  datasource:
    url: jdbc:mysql://localhost:3306/study-cloud-goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 0



