#端口和上下文配置
server:
  port: 8081
  servlet:
    context-path: /api/goods

#spring应用和数据源配置
spring:
  application:
    name: module-goods
  datasource:
    url: jdbc:mysql://localhost:3306/study-cloud-goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 0
  cloud:
    sentinel:
      datasource:
        r1:   #表示流控规则
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848 # Nacos地址
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow  #规则类型，flow表示流控类型
        r2:   #表示熔断规则
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848 # Nacos地址
            data-id: ${spring.application.name}-sentinel-degrade
            group-id: DEFAULT_GROUP
            rule-type: degrade  #规则类型，degrade表示熔断类型

