#端口和上下文配置
server:
  port: 8082
  servlet:
    context-path: /api/user

#spring应用和数据源配置
spring:
  application:
    name: module-user
  datasource:
    url: jdbc:mysql://localhost:3306/study-cloud-user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 0



